### ISSUE TITLE
Feature/milestone/01-issue/01

### ISSUE THREAD

**Issue by brobro332** [brobro332/java-co-working#6]
# 업무
- [x] `Milestone` `CRUD API` 개발
- [x] 전체 도메인 설계
- [x] `MemberTask` 개발
- [x] 전체 비즈니스 로직 재개발
- [x] 전체 테스트 코드 재개발

**Comment by brobro332** [comment]
모든 목록 완료 : `ERD` 수정하여 `PUSH` 및 `MERGE` 예정
